### ISSUE TITLE
Setting up a Docker based Development environment

### ISSUE THREAD

**Issue by markulf** [mitls/mitls-fstar#123]
This is likely just a question of updating
https://github.com/mitls/mitls-fstar/wiki/Setting-up-a-Docker-based-Development-environment
to include some Windows details.

We should also warn against mounting a repository that is already otherwise in use, as I suspect this would lead to trouble.

**Comment by vkanne-msft** [comment]
@markulf most of the instructions work for windows. Is there something specific you are looking for, apart from mounting issues ?

**Comment by markulf** [comment]
General testing and taking users by the hand. We should probably link back to the star docker wiki as well.

**Comment by markulf** [comment]
@added a link back to the F* docker wiki page. My impression is that the setup is not yet widely used and thus mostly untested.

**Comment by markulf** [comment]
@protz should the docker related setup instructions be included here? 
https://github.com/mitls/mitls-fstar/wiki/Development-environment

There also seems to be a trend towards bash-for-windows instead of cygwin.

**Comment by msprotz** [comment]
Bash for Windows is a "hack"; you might as well be using Linux in that case, because the programs you generate and compile are completely "foreign"; they can't be launched from the explorer; they can't be used by "native" windows programs; etc.

Bash for Windows is a workaround for the lack of support of OCaml on Windows. I'm fine with documenting it and saying we've had relatively good success (with master z3 and master F*), but it should be clearly stated that you're working in a foreign toolchain and that cross-compilation from gnu/linux on windows to native windows just does not exist.

**Comment by msprotz** [comment]
I'd be in favor of listing the docker instructions in F*'s INSTALL.md and making a note in mitls's [Development Environment] page

**Comment by vkanne-msft** [comment]
we have to reconcile the two docker setups between F* and mitls-fstar. If we can use DockerFile from F* and get rid of our DockerFile it should help reduce the redundancy.

**Comment by markulf** [comment]
there are also 3 different tocker files in F* one without emacs, one with emacs, and one with command line emacs only, that seems a bit of overkill as well.

**Comment by vkanne-msft** [comment]
I agree. We should converge all of those into 1.

**Comment by vkanne-msft** [comment]
I changed mitls wiki to use Docker from fstarlang/fstar. I find it much simpler and easier to use.

**Comment by markulf** [comment]
Does this mean the issue can be closed?

**Comment by vkanne-msft** [comment]
Yes we can close this.
