### ISSUE TITLE
TLSConstants.fst

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#15]
Verifies, but has ~10 admits
Requires improvement from F* to handle nested recursive functions (Nik)
Nik to remove all existing admits
Later, refactor TLSConstants moving parts of it to CoreCrypto (not yet assigned)

**Comment by s-zanella** [comment]
Took over this one.
Removed all admits and proved several inversion lemmas. I believe that by now most or all things that are TLS-independent have been moved to CoreCrypto.

I'm not closing the issue because I had to make some `let recs` top-level; otherwise we hit the "Stack overflow" bug during extraction. We should revisit this when there is better support for `let recs` in F*.

**Comment by nikswamy** [comment]
Thanks for taking this over, Santiago. 

Is it easy to construct a repro for the stack overflow? We had a similar problem earlier which I fixed, but I guess my fix is incomplete.

**Comment by s-zanella** [comment]
To reproduce this in `TLSConstants.fst`, move the top-level `configurationExtensionsBytes_aux` back inside `configurationExtensionsBytes`, then run `make tls-gen` to get a stack overflow.

For reference, this is the problematic piece of code
```
val configurationExtensionsBytes: list configurationExtension -> Tot bytes
let configurationExtensionsBytes ce =
  let rec configurationExtensionsBytes_aux (b:bytes{length b < 65536}) (ces:list configurationExtension): Tot (b:bytes{length b < 65536}) (decreases ces) =
  match ces with
  | [] -> b
  | ce::ces ->
    if length (b @| configurationExtensionBytes ce) < 65536 then
      configurationExtensionsBytes_aux (b @| configurationExtensionBytes ce) ces
    else b
  in
  let b = configurationExtensionsBytes_aux empty_bytes ce in
  lemma_repr_bytes_values (length b);
  vlbytes 2 b
```

**Comment by nikswamy** [comment]
thanks for the report, For the record, manage to minimize this to:

```
module Test
assume type bytes
assume val empty_bytes : bytes
assume val op_At_Bar: bytes -> bytes -> Tot bytes
assume val natBytes: ce:nat -> Tot bytes

val natsBytes: list nat -> Tot bytes
let natsBytes ce =
  let rec natsBytes_aux (b:bytes) (ces:list nat): Tot bytes =
  match ces with
  | [] -> b
  | ce::ces -> natsBytes_aux (b @| natBytes ce) ces in
  let b = natsBytes_aux empty_bytes ce in
  b @| b

let test (sce:list nat) : Tot bytes = natsBytes sce 
```

Repro by:

```$ fstar --lax --explicit_deps --universes test.fst --codegen OCaml
Extracting module Test

$ echo $?
127```

**Comment by nikswamy** [comment]
In case you're curious, here's a description of the bug fix:

When normalizing `match e with pi -> ei`, in case the reduction is stuck (e.g., because it's an open term), then we still can normalize each branch `ei`, but since the context for `ei` may not be consistent, we have to be careful to not reduce any fixed points within `ei`, since it may diverge. I was already attempting to forbid fixed point reductions in `ei`, but I had a bug that was only forbidding reducing top-level fixpoints, not nested ones. I implemented a different mechanism for forbidding these reductions that should be treat nested and top-level `let rec`s uniformly. 

Thanks for the bug report.

**Comment by s-zanella** [comment]
There is a still one top-level `let rec` that could be removed, but an open issue in F* prevents us from doing so.

Reopening so we remember to revisit it once we have a fix for https://github.com/FStarLang/FStar/issues/533

**Comment by s-zanella** [comment]
Used Nik's workaround for #533.
