### ISSUE TITLE
Support certificate checking

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#24]
Depends on #13.
Initially we may just accept any chain, or even any signature.

**Comment by s-zanella** [comment]
We now have functions for validating chains and ECDSA/DSA/RSA signatures in CoreCrypto, Cert, and Signature. We need better support for loading private keys and surface it all the way to the Signature/Cert modules.

We need more test vectors, using chains found in the wild. Currently we only have one for each type of key and use self-signed certificates. 
Maybe use Frankencerts at some point?

**Comment by ad-l** [comment]
We do have Cert.validate that wraps openssl verify cert. Further progress depends on miPKI which will have its own thing

**Comment by markulf** [comment]
Certificate validation also is related to handshake configurations which play an important role in the crypto modelling, e.g. for downgrade. 
Ultimately certificate validation determine which public keys a party accepts and whether their configuration gives them static security, i.e. security no matter what they do, rather than dynamic security, i.e. security if they happen to negotiate a good long-term key.

So there are many questions open in the modelling, but I would only reopen this issue once our thinking/miPKI evolves enough to revisit the code.
