### ISSUE TITLE
Functional Handshake module (no resumption, rekey, rehandshake)

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#35]
Top-level interface to sub-protocol. Owned by @karthikbhargavan 
Reconcile with Handshake.fsti.

**Comment by s-zanella** [comment]
`Handshake.fsti` is gone. We moved declarations to `Handshake.fst` to be able to work on the file interactively (due to interactive work not working with split files). 

I still see a few assumed functions in `Handshake.fst` and one FIXME in `preparseServerHello`, but the bulk of the work should be almost done. @prosecco or #ad-l should be able to better assess how much is left.

**Comment by s-zanella** [comment]
It looks like this task is complete for TLS 1.3.
Is it also done for TLS 1.2? I can't see any way of getting a TLS 1.2 StAE instance from Handshake (or KeySchedule).

**Comment by ad-l** [comment]
I'm pushing the StAE changes for 1.2 now
