### ISSUE TITLE
Platform.Bytes

### ISSUE THREAD

**Issue by sishtiaq** [mitls/mitls-fstar#6]
Make the file safe; make sure the type is abstract
Understand which miTLS parts actually need bytes; which parts can get away with immutable strings
Rename bytes into something else to clear the confusion (Pervasive.bytes != Platform.Bytes.bytes)
Figure out whether there's a performance hit when the Platform.Bytes.bytes are converted into C-style buffers in the C side of CoreCrypto
Be compatible with JK's style in the ECC paper
1. Platform.Bytes.fst
   a) Remove all the assumes, retain the representation of bytes as seq uint8 although make it abstract
   b) Extract it to ML
   c) Be able to run against it, very inefficiently
2. InfixBytes.fst (Should be done before the interns come)
   a) Backport the Bytes module from Platform.ml to a .fst
   b) Using a byte sequence with length and infix indexes
   c) Verify it against the same interface as in (1)
   d) Extract back to .ml
   e) Should  get exactly the same performance profile as the original Platform.ml
3. Stateful bytes library (Jonathan + Perry in the summer)
   a. Mutable arrays of bytes
   b. With some kind of ownership discipline over sub-arrays
   c. Pretty open-ended … but we really need something effective here for performance
   d. But, how to retain a mostly pure style of verification despite the underlying mutable state

**Comment by ad-l** [comment]
The important bit for milestone 0 have been done; postponing the later points (stateful byte library and InfixBytes) to milestone 1.3

**Comment by markulf** [comment]
@msprotz @nikswamy @fournet we had some discussions on this today, is this a good place to document them?

**Comment by vkanne-msft** [comment]
Absolutely. Please add them

**Comment by sishtiaq** [comment]
Not urgent for Milestone 1.

**Comment by s-zanella** [comment]
We will eventually need to use `FStar.Buffer` instead of `Platform.Bytes`.
Recent discussion on Slack:

fournet [16:04]
Bumped into a slippery (recurrent) problem with Platform.bytes: bytes are supposed to be comparable sequences, but at runtime require a custom call to `equalbytes` to be sound. They should probably be made abstract. Also, how to anticipate the switch to lower-level bytes?

This is problematic in most of our code for parsing and formatting, leading both to unexpected behaviour and some ML-level type errors.

nik [16:27] 
how come we have hasEq on bytes?

fournet [16:39] 
We agree this it not right! They are officially `seq byte`, so I believe the assume hasEq is not necessary as long as they remain concrete, which is the root problem. But I am concerned  we are using bytes-as-sequences in many places. One solution, quite heavy and similar to what we do e.g. with buffers, is to make bytes abstract with a coercion to ghost sequences for specification purposes. Another is to pick a more naive representation of bytes such that primitive ocaml equality coincides with `Seq.equal #byte` For the record, `platform.ml` defines
```  let equalBytes (b1:bytes) (b2:bytes) =
      if length b1 = length b2 then
         let cb1 = get_cbytes b1 in
         let cb2 = get_cbytes b2 in
         let ok = ref true in
         for x = 0 to b1.length-1 do
             ok := String.get cb1 x = String.get cb2 x && !ok;
         done;
         !ok
      else false```

**Comment by BarryBo** [comment]
Stale.  Closing.
