### ISSUE TITLE
Implement sample server and client apps in mitls.exe tool to test top-level API 

### ISSUE THREAD

**Issue by vkanne-msft** [mitls/mitls-fstar#76]

**Comment by s-zanella** [comment]
The TLS 1.2 and 1.3 sample server and client applications are going to be part of the `mitls.exe` command-line tool.

@ad-l is working on adding a `-tlsapi` flag to the tool that will use the top-level TLS API instead of scripted sequences of messages like in `test/TestClient{13}.fst` and `test/TestServer{13}.fst`

**Comment by ad-l** [comment]
Client is complete, server in progress

**Comment by ad-l** [comment]
Server is complete

**Comment by s-zanella** [comment]
Reopening. Please close this once we have client and server apps for TLS 1.2 working through mitls.exe.

**Comment by vkanne-msft** [comment]
@s-zanella can we close this ?

**Comment by s-zanella** [comment]
Yes. The client and server apps for TLS 1.2 have now been implemented and tested against OpenSSL
