### ISSUE TITLE
Add support for ChaCha20 + Poly1305 AEAD

### ISSUE THREAD

**Issue by s-zanella** [mitls/mitls-fstar#83]
See https://tools.ietf.org/html/rfc7539#section-2.8 for the specification of the AEAD construction.

**Comment by fournet** [comment]
Looking at this integration, now that we have F* implementations for both algorithms. It may also be interesting to manually interleave the 2 algorithms to scan the data only once. Anyone working on it?

**Comment by fournet** [comment]
See also https://tools.ietf.org/html/draft-ietf-tls-chacha20-poly1305-04

**Comment by ad-l** [comment]
ChaCha20/poly1305 is happening on the Inria side. Karthik tols us in the miTLS call that they have an almost complete F* CoreCrypto provider (only sig and x509 missing). I'm happy to add the ChaCha20 ciphersuites to TLSConstants but there is also some work to do in the record modules in order to integrate.

**Comment by fournet** [comment]
Yes; I am discussing it with JK. Adding and verifying the code for AEAD from encrypt-then-MAC would yield a nice, standard example for mitls crypto; there are also interesting low-level performance issues.

Do we have an implementation of AEAD based on them yet?

**Comment by prosecco** [comment]
The plan, with JK and others over here, is to have a pure F* version of CoreCrypto that includes: EC (P-256, X25519), AEAD (AES-GCM,  Chacha20-Poly1305), and HASH (SHA-256, HMAC, HKDF)
These will be lax-typechecked in HST, will extract to OCaml and then (hopefully) to C
Ben is currently working on implementing one AEAD mode based on Chacha20-Poly1305
Jianyang is implementing AES-GCM

**Comment by s-zanella** [comment]
What's the status of the AEAD mode based on Chacha20-Poly1305? 
Would that be in the form of a miTLS module at the same level as AEAD_GCM?

Cédric mentioned it would be nice to work on implementing a generic AEAD module for EtM, with Chacha20-Poly1305 as an instance. We could work on that in Cambridge if Ben or JK are visiting, or coordinate via Skype if not. We would need to decide how to call into the Chacha20-Poly1305 code, and perhaps resolve the monad mismatch between HH and HST.

**Comment by fournet** [comment]
Benjamin: do you have some code for it already? 
I am prototyping AEAD, to understand how to naturally call JK's primitives (and possibly suggest some refactoring). Will check in e.g. some resulting EtM.fst in miTLS-fstar.
We don't quite understand how to switch from one state monad to another, e.g. to integrate with miTLS.
It is also probably worth comparing with OpenSSL implementations, for performance and correctness.

**Comment by jkzinzindohoue** [comment]
I think that this monad mismatch is interesting because HST is really a refinement of HH. 
Benjamin had code for the AEAD mode on Chacha-Poly in the 'simple' ST monad at https://github.com/mitls/hacl-star/blob/master/crypto/symmetric/AEAD.ChaCha20_Poly1305.fst. I will write it for HST this afternoon and post a pointer to it here.

**Comment by beurdouche** [comment]
Ok, @jkzinzindohoue if you do port it to HST before monday, don't forget the check on tags in the decryption function... ;)

**Comment by fournet** [comment]
Would be curious to discuss the coding, e.g. to avoid copying.

**Comment by fournet** [comment]
I had a look at the description of poly1305, http://cr.yp.to/mac/poly1305-20050329.pdf. The securoty proof seems largely f*-able.

**Comment by jkzinzindohoue** [comment]
I have written an first draft of the AEAD mode in https://github.com/FStarLang/FStar/blob/master/examples/low-level/AEAD.Chacha20_Poly1305.fst.
The issue is that there are quite a few unnecessary copies due to some conversions between `buffer 'a` and `buffer 'b`.
I am make an attempt to write everything on top of `bytes` that could be interpreted as bytes as well as arrays of any type, to write something closer to C pointer casts. That should help performance a lot.
You can have a look at https://github.com/FStarLang/FStar/blob/master/examples/low-level/Low.Bytes.fst.

**Comment by s-zanella** [comment]
Done. Using OpenSSL or verified implementation in Hacl*, depending on the crypto provider.
